spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/inventorymgmtdb"
    driverClassname: com.mysql.cj.jdbc.Driver
    username: root
    password: Basant123@
  jpa:
    show-sql: true
    generate-ddl: true
stock:
  transportType: air
  slaDays: 2
